NHSDigital/uec-cm

.github/workflows/check-python-black-format.yaml, .github/workflows/check-python-flake-rules.yaml, .github/workflows/check-terraform-format.yaml, .github/workflows/cicd-pipeline.yaml, README.md, infrastructure/README.md, scripts/functions/git-functions.sh, scripts/functions/test-git-functions.sh, scripts/git/commit-msg, scripts/git/git-config-set-up.sh, scripts/git/pre-commit, scripts/githooks/commit-msg, scripts/githooks/git-branch-commit-msg.sh, scripts/githooks/git-commit-msg.sh, scripts/githooks/python-black-pre-commit.sh, scripts/githooks/python-flake-pre-commit.sh, scripts/githooks/terraform-pre-commit.sh
Added github hooks and updated readme file
Addition of github hooks to ensure consistent development processes
---
=> DR-71 Update readme and add githooks

.github/workflows/cicd-pipeline.yaml, .github/workflows/cloc-repository.yaml, .gitleaks.toml, scripts/cloc-repository.sh, scripts/functions/terraform-functions.sh, scripts/git/git-config-set-up.sh, scripts/infra-deploy.sh, scripts/variables-default.sh, scripts/variables-dev.sh, scripts/variables-test.sh
Updating file structure and configuration to match what we have in the 'sec-account-mngt' repo and that is an updated repo.
This change is required in order to make sure that all our repos have a similar file structure and configuration to keep up consistency.
---
=> DR-320 Repo structure update

infrastructure/capacity_management.tfvars, infrastructure/stacks/capacity_management/apig-healthcare-service.tf, infrastructure/stacks/capacity_management/lambda.tf, infrastructure/stacks/capacity_management/variables.tf
Conect api-gateway route to the healthcare-services lambda
- [x ] New feature (non-breaking change which adds functionality)
- [ x] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [x ] I have followed the code style of the project
---
=> DR-352 add healthcare-services api route

infrastructure/stacks/github-runner/uec-github-runner-iam-services.json
Work on Athena terraform requires additional permissions for github runner
---
=> DR-406 Add role policy perms

.github/workflows/orchestrate-terraform.yaml
Switch workflow to apply terraform rather than plan
Note we will need to tidy up non default workspaces 
---
=> DR-412 Apply app terraform

.github/workflows/deploy-application-infrastructure.yaml, .github/workflows/deploy-bootstrap.yaml, .github/workflows/deploy-infrastructure-stack.yaml, .github/workflows/pipeline-deploy-app-develop.yaml, .github/workflows/pipeline-deploy-app-test.yaml, .github/workflows/pipeline-deploy-bootstrap.yaml
Renaming of github workflows to clearly separate automated workflows (known as pipelines) and reusable workflows (i.e. workflows that are invoked by automated pipelines)
Clarity of what the workflow does.
---
=> DR-406 Pipeline rename refactor

infrastructure/stacks/capacity_management/scripts/database_populator/database_populator.py
=> DR-407 Org data load

.github/workflows/action-infrastructure-stack.yaml, .github/workflows/pipeline-deploy-app-develop.yaml, .github/workflows/pipeline-deploy-app-test.yaml, .github/workflows/validate-terraform.yaml
Workflows refactored to derive the version of terraform once and use it to a) validate the IAC and b) plan/apply/destroy  resources. Current workflows call it multiple times (at cost of approx 4 seconds a call) 
---
=> DR-354 Derive terraform version once

infrastructure/stacks/capacity_management/scripts/database_populator/database_populator.py
=> DR-415 Refactor load script

.gitignore, tests/ui/.github/workflows/playwright.yml, tests/ui/cucumber.json, tests/ui/package-lock.json, tests/ui/package.json, tests/ui/playwright.config.ts, tests/ui/src/hooks/hooks.ts, tests/ui/src/hooks/pageFixture.ts, tests/ui/src/pages/searchPage.ts, tests/ui/src/utilities/init.ts, tests/ui/test/features/search.feature, tests/ui/test/steps/search.steps.ts
Initial set up of the CM UI test framework to include a sample test scenario
---
=> DR-448 Initial CM UI test framework

.github/workflows/tag-code.yaml, scripts/functions/git-functions.sh, scripts/tag-code.sh
=> DR-397 test ready tag

.github/workflows/pipeline-deploy-app-test.yaml
=> DR-410 Deploy to test using test ready tag

.github/workflows/deploy-bootstrap.yaml, .github/workflows/manual-deploy-tagged-code.yaml, .github/workflows/pipeline-deploy-bootstrap.yaml
Bug fix to remove stray single quote and refactor bootstrap deployment
---
=> DR-436 Bug fix deployment to test

.github/workflows/deploy-bootstrap.yaml, .github/workflows/validate-terraform.yaml
Validate boostrap tf against default and parametise region
---
=> DR-436 Validate bootstrap against default

.github/workflows/action-infrastructure-cleardown.yaml, .github/workflows/cleardown-terraform-state.yaml, .github/workflows/pipeline-infrastructure-cleardown.yaml, scripts/branch-name-workspace.sh, scripts/cleardown-terraform-state.sh, scripts/functions/git-functions.sh
=> DR-562 Infra cleardown pipeline

.github/workflows/cleardown-terraform-state.yaml, scripts/cleardown-terraform-state.sh
=> DR-562 Bugfix terraform state cleardown

infrastructure/modules/cloudfront/main.tf
=> DR-999 Fixed issue with cloudfront name not being unique

infrastructure/modules/cloudfront/main.tf, infrastructure/modules/cloudfront/variables.tf, infrastructure/stacks/application/frontend.tf
=> DR-999 Fixed issue that CloudFront name was not unique (version 2)

.github/workflows/build-and-deploy-react-app.yaml, scripts/githooks/front-end-npm-lint-pre-commit.sh, src/frontend/.eslintrc.json, src/frontend/package-lock.json, src/frontend/package.json, src/frontend/src/App.tsx, src/frontend/src/components/header.tsx, src/frontend/src/index.tsx
=> DR-666 Eslint accessibility setup

src/frontend/src/App.test.tsx, src/frontend/src/App.tsx, src/frontend/src/components/banner/__tests__/banner.test.tsx, src/frontend/src/components/banner/index.tsx, src/frontend/src/components/banner/interface.ts, src/frontend/src/components/cardGroup/__tests__/cardGroup.test.tsx, src/frontend/src/components/cardGroup/index.tsx, src/frontend/src/components/cardGroup/interface.ts, src/frontend/src/components/header/__tests__/header.test.tsx, src/frontend/src/components/header/index.tsx, src/frontend/src/components/header/styles.css, src/frontend/src/pages/organisations/cards.ts, src/frontend/src/pages/organisations/index.tsx, src/frontend/src/pages/organisations/styles.css
=> DR-689 Initial gds react framework components

scripts/ui-tests.sh, tests/ui/package-lock.json, tests/ui/package.json, tests/ui/src/config/.env.dev, tests/ui/src/config/env.ts, tests/ui/src/hooks/hooks.ts, tests/ui/src/pages/searchPage.ts, tests/ui/src/utilities/cloudFront.ts, tests/ui/test/features/search.feature, tests/ui/test/steps/search.steps.ts
=> DR-617 Adding test for cloudfront domain

.github/workflows/build-and-deploy-react-app.yaml, .github/workflows/pipeline-deploy-app-test.yaml, infrastructure/application.tfvars, infrastructure/dev.tfvars, infrastructure/modules/s3/main.tf, infrastructure/modules/s3/variables.tf, infrastructure/stacks/application/frontend.tf, infrastructure/stacks/application/s3_datasource.tf, infrastructure/stacks/application/variables.tf
=> DR-632 Spin up cm resources in dos dev account

src/frontend/src/components/organisations/search/__tests__/index.test.tsx, src/frontend/src/components/organisations/search/index.tsx, src/frontend/src/pages/organisations/__tests__/add.test.tsx, src/frontend/src/pages/organisations/__tests__/index.test.tsx, src/frontend/src/pages/organisations/add.tsx, src/frontend/src/pages/organisations/index.tsx, src/frontend/src/pages/organisations/styles.css
=> DR-717 Search add organisation

scripts/ui-tests.sh, tests/ui/src/config/.env.dev, tests/ui/src/hooks/hooks.ts, tests/ui/src/pages/organisationsPage.ts, tests/ui/src/pages/searchPage.ts, tests/ui/src/utilities/cloudFront.ts, tests/ui/test/features/organisations.feature, tests/ui/test/features/search.feature, tests/ui/test/steps/organisations.steps.ts, tests/ui/test/steps/search.steps.ts
Based on DR-717 to enable testing of the script. 
This branch should be rebased after DR-717 has been merged to main
---
=> DR-7169 Adding ui tests for organisation search input

infrastructure/stacks/github-runner/uec-github-runner-iam-services.json
Add the required permissions for the resource level tagging for the cm repo.
https://nhsd-jira.digital.nhs.uk/browse/DR-511
---
=> DR-511 Resource tagging perms for cm

.gitignore, tests/ui/src/pages/organisationsPage.ts, tests/ui/test/features/organisations.feature, tests/ui/test/steps/organisations.steps.ts
=> DR-7181 Adding in postcode validation tests

.gitignore, tests/ui/package.json, tests/ui/src/hooks/hooks.ts, tests/ui/src/pages/searchPage.ts, tests/ui/src/utilities/accessibility.ts, tests/ui/src/utilities/fileCount.ts, tests/ui/src/utilities/init.ts, tests/ui/test/features/accessibility.feature, tests/ui/test/features/organisations.feature, tests/ui/test/steps/organisations.steps.ts, tests/ui/test/steps/search.steps.ts
=> DR-690 Implementing Axe into ui framework

tests/unit/requirements.txt
=> DR-9999 Remove unused ref to Flask

src/frontend/src/components/banner/__tests__/banner.test.tsx, src/frontend/src/components/banner/index.tsx, src/frontend/src/components/banner/interface.ts, src/frontend/src/pages/organisations/__tests__/index.test.tsx, src/frontend/src/pages/organisations/index.tsx
=> DR-758 Update organisation banner

src/frontend/src/components/cardGroup/index.tsx, src/frontend/src/components/cardGroup/interface.ts, src/frontend/src/pages/organisations/__tests__/index.test.tsx, src/frontend/src/pages/organisations/cards.ts
=> DR-759 Remove cards from org page

tests/ui/src/hooks/hooks.ts, tests/ui/src/pages/organisations-add-page.ts, tests/ui/src/pages/search-page.ts, tests/ui/test/steps/organisations-add.steps.ts, tests/ui/test/steps/search.steps.ts
Fix bug where test failures are not reported correctly on console
There was an issue where test failures were not reported to the correctly.
---
=> DR-762 Fix console reporting

tests/uiv2/.env.test, tests/uiv2/config/.env.dev, tests/uiv2/package-lock.json, tests/uiv2/package.json, tests/uiv2/pages/organisation-add-page.ts, tests/uiv2/playwright.config.ts, tests/uiv2/tests/organisation-add.spec.ts, tests/uiv2/utilities/accessibility.ts, tests/uiv2/utilities/cloudFront.ts, tests/uiv2/utilities/env.ts, tests/uiv2/utilities/fileCount.ts, tests/uiv2/utilities/init.ts
=> DR-989 Playwright without cucumber

src/frontend/src/components/cardGroup/index.tsx, src/frontend/src/components/images/rightchevron.tsx
=> DR-768 Create rightchevron icon

src/frontend/src/components/organisations/search/searchresults.tsx, src/frontend/src/hooks/useOrganisationLocationSearch.ts, src/frontend/src/mockdata/getlocations/default.json, src/frontend/src/mockdata/getlocations/london.json, src/frontend/src/mockdata/getlocations/single.json, src/frontend/src/mockdata/getorganisations/default.json, src/frontend/src/mockdata/getorganisations/london.json, src/frontend/src/mockdata/getorganisations/single.json, src/frontend/src/services/api/interface.ts, src/frontend/src/services/mocks/getLocations.ts, src/frontend/src/services/mocks/getOrganisations.ts
=> DR-765 Update mock data

src/frontend/src/components/organisations/search/__tests__/noresultsfound.test.tsx, src/frontend/src/components/organisations/search/__tests__/searchresults.test.tsx, src/frontend/src/components/organisations/search/searchresults.tsx, src/frontend/src/components/organisations/search/styles.css, src/frontend/src/components/pagination/__tests__/index.test.tsx, src/frontend/src/components/pagination/index.tsx, src/frontend/src/components/pagination/nextpagelink.tsx, src/frontend/src/components/pagination/previouspagelink.tsx, src/frontend/src/components/pagination/resultsinfo.tsx, src/frontend/src/components/pagination/styles.css, src/frontend/src/hooks/__tests__/usePagination.test.ts, src/frontend/src/hooks/usePagination.ts, src/frontend/src/mockdata/getlocations/royal.json, src/frontend/src/mockdata/getorganisations/royal.json, src/frontend/src/pages/organisations/__tests__/add.test.tsx, src/frontend/src/pages/organisations/add.tsx, src/frontend/src/services/api/__tests__/controller.test.ts, src/frontend/src/services/api/__tests__/realapi.test.ts, src/frontend/src/services/mocks/__tests__/getLocations.test.ts, src/frontend/src/services/mocks/__tests__/getOrganisations.test.ts, src/frontend/src/services/mocks/getLocations.ts, src/frontend/src/services/mocks/getOrganisations.ts
=> DR-720 Search results screen

.github/workflows/build-and-deploy-react-app.yaml, tests/ui/playwright.config.ts, tests/ui/src/pages/organisation-add-page.ts, tests/ui/src/pages/organisation-search-page.ts, tests/ui/src/utilities/accessibility.ts, tests/ui/test/specs/accessibility.spec.ts, tests/ui/test/specs/organisation-add.spec.ts, tests/ui/test/specs/organisations-search.spec.ts
=> DR-7331 Playwright ui automated tests for dr-733

tests/ui/src/pages/organisation-search-page.ts, tests/ui/src/pages/organisation-summary-page.ts, tests/ui/test/specs/organisations-search.spec.ts
Add ui automated tests for dr-802
---
=> DR-802 View organisation summary

scripts/ui-tests.sh, tests/ui/package-lock.json, tests/ui/package.json, tests/ui/playwright.config.ts, tests/ui/src/pages/organisation-search-page.ts, tests/ui/src/utilities/accessibility.ts, tests/ui/test/specs/accessibility.spec.ts, tests/ui/test/specs/organisation-add.spec.ts, tests/ui/test/specs/organisations-search.spec.ts, tests/ui/test/specs/organisations.spec.ts
=> DR-836 Standardising test formats and reporting

.github/workflows/ui-test.yaml, scripts/ui-tests.sh, tests/ui/src/pages/organisation-add-page.ts, tests/ui/src/pages/organisation-search-page.ts, tests/ui/src/pages/organisation-summary-page.ts, tests/ui/test/specs/accessibility.spec.ts, tests/ui/test/specs/organisation-add.spec.ts, tests/ui/test/specs/organisations-search.spec.ts, tests/ui/test/specs/organisations.spec.ts
=> DR-837 Bug test pipeline does not report failures

tests/ui/downloads/data.csv, tests/ui/package-lock.json, tests/ui/package.json, tests/ui/src/utilities/csvHelper.ts, tests/ui/test/specs/read-csv.spec.ts
=> DR-857 Add csvreader functions

.github/workflows/pipeline-deploy-account-infrastructure.yaml, .github/workflows/pipeline-deploy-app-develop.yaml, .github/workflows/pipeline-deploy-app-test.yaml, .github/workflows/pipeline-infrastructure-cleardown-dev.yaml, .github/workflows/pipeline-infrastructure-cleardown-test.yaml, .github/workflows/pipeline-manual-deploy-tagged-code.yaml, .github/workflows/pipeline-tag-deploy-test.yaml, tests/ui/src/utilities/s3Helper.ts
Separating the build and deploy of react app to the Test env in CM and updating the clear down workflow 
Required to meet the requirements of new workflow
---
=> DR-928 Update test and cleardown workflows

infrastructure/int.tfvars
=> DR-974 Adding in int tfvars

.github/workflows/pipeline-deploy-account-infrastructure.yaml, .github/workflows/pipeline-deploy-app-develop.yaml, .github/workflows/pipeline-deploy-app-test.yaml, .github/workflows/pipeline-infrastructure-cleardown-dev.yaml, .github/workflows/pipeline-infrastructure-cleardown-test.yaml, .github/workflows/pipeline-manual-deploy-tagged-code.yaml, .github/workflows/pipeline-tag-deploy-test.yaml
=> DR-898 Switch latest tag

infrastructure/preprod.tfvars, infrastructure/prod.tfvars
=> DR-881 Add tfvars for preprod and prod envs

.github/workflows/pipeline-deploy-account-infrastructure.yaml, .github/workflows/pipeline-deploy-app-develop.yaml, .github/workflows/pipeline-deploy-app-int.yaml, .github/workflows/pipeline-deploy-app-test.yaml, .github/workflows/pipeline-infrastructure-cleardown-dev.yaml, .github/workflows/pipeline-infrastructure-cleardown-test.yaml, .github/workflows/pipeline-manual-deploy-tagged-code.yaml, .github/workflows/pipeline-tag-deploy-int.yaml, .github/workflows/pipeline-tag-deploy-test.yaml
=> DR-1000 Change tag to latest

.github/workflows/pipeline-deploy-account-infrastructure.yaml, .github/workflows/pipeline-deploy-app-develop.yaml, .github/workflows/pipeline-deploy-app-int.yaml, .github/workflows/pipeline-deploy-app-test.yaml, .github/workflows/pipeline-deploy-app.yaml, .github/workflows/pipeline-infrastructure-cleardown-dev.yaml, .github/workflows/pipeline-infrastructure-cleardown-test.yaml, .github/workflows/pipeline-manual-deploy-tagged-code.yaml, .github/workflows/pipeline-manual-prototype_deploy.yaml, .github/workflows/pipeline-tag-deploy-int.yaml, .github/workflows/pipeline-tag-deploy-test.yaml, infrastructure/prototype.tfvars
=> DR-1048 Prototype delivery flow

.github/workflows/pipeline-deploy-account-infrastructure.yaml, .github/workflows/pipeline-deploy-app-develop.yaml, .github/workflows/pipeline-deploy-app-int.yaml, .github/workflows/pipeline-deploy-app-test.yaml, .github/workflows/pipeline-deploy-app.yaml, .github/workflows/pipeline-infrastructure-cleardown-dev.yaml, .github/workflows/pipeline-infrastructure-cleardown-test.yaml, .github/workflows/pipeline-manual-deploy-tagged-code.yaml, .github/workflows/pipeline-tag-deploy-int.yaml, .github/workflows/pipeline-tag-deploy-test.yaml
=> DR-1065 Move from v36 to latest

.github/workflows/pipeline-deploy-account-infrastructure.yaml, .github/workflows/pipeline-deploy-app-test.yaml, infrastructure/preprod.tfvars, infrastructure/prod.tfvars, infrastructure/stacks/application/data.tf
=> DR-1029 fix test deploy

.github/workflows/pipeline-deploy-account-infrastructure.yaml
=> DR-1030 No cm github runner required in int

.github/workflows/pipeline-deploy-account-infrastructure.yaml
=> DR-1030 Restore github runner to int flow

.github/workflows/pipeline-deploy-app-preprod-prod.yaml
Implement prod preprod workflow
---
=> DR-1098 Implement prod preprod workflow

tests/ui/test/specs/accessibility.spec.ts, tests/ui/test/specs/organisation-add.spec.ts, tests/ui/test/specs/organisations-search.spec.ts, tests/ui/test/specs/organisations.spec.ts, tests/ui/test/specs/read-csv.spec.ts, tests/ui/test/specs/read-s3-csv.spec.ts
=> DR-1109 Updated read csv test

src/frontend/src/prototype/admin/accountPermissions.tsx
=> DR-1123 Prototype added information text on account permissions

README.md, src/frontend/README.md
Update to frontend documentation in both root readme.md and src/frontend/readme.md
Needed to facilitate new joiners starting and running the frontend project
- [X ] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
---
=> DR-1114 Update root readme and frontend readme

tests/ui/src/pages/questionnaire-check-your-answers-page.ts, tests/ui/src/pages/view-locations-page.ts, tests/ui/test/specs/check-your-answers.spec.ts, tests/ui/test/specs/view-questionnaire.spec.ts
Added view update summary tests
Added new test check-your-answers.spec.ts
---
=> DR-1158 Added view update summary tests

.github/CODEOWNERS, infrastructure/modules/dynamodb/main.tf, infrastructure/modules/dynamodb/variables.tf, infrastructure/stacks/terraform_management/dynamodb.tf
=> DR-1173 Protect tf state table from deletion

.github/workflows/pipeline-deploy-account-infrastructure.yaml
=> DR-1155 Suppress updates to test

README.md, docs/user-guides/Git_branching_strategy.md, scripts/functions/git-functions.sh, scripts/functions/test-git-functions.sh, scripts/githooks/git-commit-msg.sh
=> FDOS-56 Update branch naming and commit message rules

.github/workflows/pipeline-deploy-app-non-prod.yaml, tests/ui/.github/workflows/playwright.yml
Following guidance received moving up from v3 to v4 - most cases use dos-management reusable actions - just one outlier
---
=> FDOS-120 Upload artifact to v4
